const Affiliate = require('../models/Affiliate');
const User = require('../models/User');

// POST /api/affiliates/register
exports.registerAffiliate = async (req, res) => {
  try {
    const existing = await Affiliate.findOne({ user: req.user._id });
    if (existing) {
      return res.status(400).json({ message: 'Affiliate profile already exists' });
    }

    const { payoutMethod, mpesaNumber, bankDetails } = req.body;

    const affiliate = await Affiliate.create({
      user: req.user._id,
      payoutMethod,
      mpesaNumber,
      bankDetails,
      // affiliateCode auto-generated by pre('save') hook
    });

    // Upgrade user role
    await User.findByIdAndUpdate(req.user._id, { role: 'affiliate' });

    res.status(201).json({ success: true, affiliate });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
};

// GET /api/affiliates/profile
exports.getAffiliateProfile = async (req, res) => {
  try {
    const affiliate = await Affiliate.findOne({ user: req.user._id })
      .populate('user', 'name email')
      .populate('orders', 'orderNumber totalPrice createdAt');
    if (!affiliate) return res.status(404).json({ message: 'Affiliate not found' });
    res.json({ success: true, affiliate });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
};

// GET /api/affiliates/stats
exports.getAffiliateStats = async (req, res) => {
  try {
    const affiliate = await Affiliate.findOne({ user: req.user._id });
    if (!affiliate) return res.status(404).json({ message: 'Affiliate not found' });

    res.json({
      success: true,
      stats: {
        affiliateCode: affiliate.affiliateCode,
        totalClicks: affiliate.totalClicks,
        totalOrders: affiliate.totalOrders,
        totalSales: affiliate.totalSales,
        totalEarned: affiliate.totalEarned,
        totalPaid: affiliate.totalPaid,
        pendingBalance: affiliate.pendingBalance,
        conversionRate: affiliate.conversionRate,
        currentTier: affiliate.currentTier,
        status: affiliate.status,
      }
    });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
};

// POST /api/affiliates/track-click — increment click count
exports.trackClick = async (req, res) => {
  try {
    const { affiliateCode } = req.body;
    if (!affiliateCode) return res.status(400).json({ message: 'Affiliate code required' });

    await Affiliate.findOneAndUpdate(
      { affiliateCode, status: 'active' },
      { $inc: { totalClicks: 1 }, lastActiveAt: new Date() }
    );

    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
};